// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ49LIiZkU7HERPj3SX0-AnYzXlOn1Qyc',
    appId: '1:832501389233:web:c0be43c7ea4ec796d74f90',
    messagingSenderId: '832501389233',
    projectId: 'flutter-web-dev1',
    authDomain: 'flutter-web-dev1.firebaseapp.com',
    storageBucket: 'flutter-web-dev1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxAfMGebQktlvAJIaxrYZZfbOiNxAK1_A',
    appId: '1:832501389233:android:cefc1e0cd1f62782d74f90',
    messagingSenderId: '832501389233',
    projectId: 'flutter-web-dev1',
    storageBucket: 'flutter-web-dev1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-B4e9WDRR7_yOmqeDkSWvgTjkZiXcpJk',
    appId: '1:832501389233:ios:28648a5ad4ca35e6d74f90',
    messagingSenderId: '832501389233',
    projectId: 'flutter-web-dev1',
    storageBucket: 'flutter-web-dev1.appspot.com',
    iosBundleId: 'com.example.kursovaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-B4e9WDRR7_yOmqeDkSWvgTjkZiXcpJk',
    appId: '1:832501389233:ios:28648a5ad4ca35e6d74f90',
    messagingSenderId: '832501389233',
    projectId: 'flutter-web-dev1',
    storageBucket: 'flutter-web-dev1.appspot.com',
    iosBundleId: 'com.example.kursovaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ49LIiZkU7HERPj3SX0-AnYzXlOn1Qyc',
    appId: '1:832501389233:web:384aadbb7e3e6781d74f90',
    messagingSenderId: '832501389233',
    projectId: 'flutter-web-dev1',
    authDomain: 'flutter-web-dev1.firebaseapp.com',
    storageBucket: 'flutter-web-dev1.appspot.com',
  );
}
